version: '3.1'

services:

  db:
    image: postgres
    networks:
      - food-delivery-network
    restart: always
    container_name: food-delivery
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: tuandat1601
      POSTGRES_DB: mydatabase
      POSTGRES_USER: tuandat
networks:
      food-delivery-network:
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080